// Generated by Melange

import * as Stdlib__Float from "melange/float.js";
import * as Trading_core__Symbol from "../symbol.js";
import * as Trading_core__Types from "../types.js";

function generate(symbol, bid, ask, volatility, base_spread_bps, inventory, max_inventory, now) {
  const mid = (bid + ask) / 2.0;
  const vol_mult = Stdlib__Float.max(1.0, volatility / 0.15);
  const half_spread = mid * base_spread_bps / 10000.0 * vol_mult / 2.0;
  const skew = max_inventory <= 0.0 ? 0.0 : inventory / max_inventory * half_spread;
  const buy_price = mid - half_spread - skew;
  const sell_price = mid + half_spread - skew;
  const abs_inv = Math.abs(inventory);
  if (abs_inv >= max_inventory) {
    return /* [] */ 0;
  }
  const s = Trading_core__Symbol.create(symbol);
  let sym;
  sym = s.TAG === /* Ok */ 0 ? s._0 : symbol;
  const strength = {
    TAG: /* Moderate */ 1,
    _0: 0.5
  };
  const buy_signal = {
    strategy: /* Market_making */ 4,
    symbol: sym,
    side: /* Buy */ 0,
    strength: strength,
    target_price: buy_price,
    max_position_pct: 0.15,
    timestamp: now
  };
  const sell_signal = {
    strategy: /* Market_making */ 4,
    symbol: sym,
    side: /* Sell */ 1,
    strength: strength,
    target_price: sell_price,
    max_position_pct: 0.15,
    timestamp: now
  };
  return {
    hd: buy_signal,
    tl: {
      hd: sell_signal,
      tl: /* [] */ 0
    }
  };
}

function is_enabled(phase) {
  return Trading_core__Types.strategy_enabled_for_phase(phase, /* Market_making */ 4);
}

const pnl_validated = false;

export {
  generate,
  is_enabled,
  pnl_validated,
}
/* Stdlib__Float Not a pure module */
