// Generated by Melange

import * as Stdlib__Float from "melange/float.js";
import * as Trading_core__Symbol from "../symbol.js";

function generate(symbol, _price, sma20, param, z, adf_stat, hurst, now) {
  const is_stationary = adf_stat < -2.86 && hurst < 0.5;
  if (!is_stationary) {
    return;
  }
  const signal_side = z <= -2.0 ? /* Buy */ 0 : (
      z >= 2.0 ? /* Sell */ 1 : (Math.abs(z) < 0.5, undefined)
    );
  if (signal_side === undefined) {
    return;
  }
  const abs_z = Math.abs(z);
  const raw_conf = (abs_z - 2.0) / 1.0;
  const conf = Stdlib__Float.max(0.5, Stdlib__Float.min(1.0, 0.5 + raw_conf * 0.5));
  const strength = conf > 0.8 ? ({
      TAG: /* Strong */ 0,
      _0: conf
    }) : (
      conf > 0.5 ? ({
          TAG: /* Moderate */ 1,
          _0: conf
        }) : ({
          TAG: /* Weak */ 2,
          _0: conf
        })
    );
  const s = Trading_core__Symbol.create(symbol);
  let sym;
  sym = s.TAG === /* Ok */ 0 ? s._0 : symbol;
  return {
    strategy: /* Mean_reversion */ 0,
    symbol: sym,
    side: signal_side,
    strength: strength,
    target_price: sma20,
    max_position_pct: 0.15,
    timestamp: now
  };
}

function should_exit(z) {
  return Math.abs(z) < 0.5;
}

function is_stopped(z) {
  return Math.abs(z) >= 3.0;
}

function passes_stationarity_gate(adf_stat, hurst) {
  if (adf_stat < -2.86) {
    return hurst < 0.5;
  } else {
    return false;
  }
}

export {
  generate,
  should_exit,
  is_stopped,
  passes_stationarity_gate,
}
/* Stdlib__Float Not a pure module */
