// Generated by Melange

import * as Caml_obj from "melange.js/caml_obj.js";
import * as Stdlib__Float from "melange/float.js";
import * as Trading_core__Symbol from "../symbol.js";
import * as Trading_core__Types from "../types.js";

function generate(symbol, ema12, ema26, prev_ema12, prev_ema26, sma50, sma200, rsi14, rel_volume, price, now) {
  if (rel_volume < 1.5) {
    return;
  }
  const uptrend = Caml_obj.caml_greaterthan(sma50, sma200);
  const downtrend = Caml_obj.caml_lessthan(sma50, sma200);
  const bullish_cross = Caml_obj.caml_lessequal(prev_ema12, prev_ema26) && ema12 > ema26;
  const bearish_cross = Caml_obj.caml_greaterequal(prev_ema12, prev_ema26) && ema12 < ema26;
  const rsi_oversold = rsi14 < 30.0;
  const rsi_overbought = rsi14 > 70.0;
  const signal_side = bullish_cross && uptrend && !rsi_overbought ? /* Buy */ 0 : (
      bearish_cross && downtrend && !rsi_oversold ? /* Sell */ 1 : undefined
    );
  if (signal_side === undefined) {
    return;
  }
  let rsi_bonus;
  rsi_bonus = signal_side === /* Buy */ 0 ? (
      rsi_oversold ? 0.15 : 0.0
    ) : (
      rsi_overbought ? 0.15 : 0.0
    );
  const vol_bonus = rel_volume >= 2.0 ? 0.1 : 0.0;
  const conf = Stdlib__Float.min(1.0, 0.6 + rsi_bonus + vol_bonus);
  const strength = conf > 0.8 ? ({
      TAG: /* Strong */ 0,
      _0: conf
    }) : (
      conf > 0.5 ? ({
          TAG: /* Moderate */ 1,
          _0: conf
        }) : ({
          TAG: /* Weak */ 2,
          _0: conf
        })
    );
  const ema_diff = Math.abs(ema12 - ema26);
  let target;
  target = signal_side === /* Buy */ 0 ? price + ema_diff : price - ema_diff;
  const s = Trading_core__Symbol.create(symbol);
  let sym;
  sym = s.TAG === /* Ok */ 0 ? s._0 : symbol;
  return {
    strategy: /* Momentum */ 3,
    symbol: sym,
    side: signal_side,
    strength: strength,
    target_price: target,
    max_position_pct: 0.15,
    timestamp: now
  };
}

function is_enabled(phase) {
  return Trading_core__Types.strategy_enabled_for_phase(phase, /* Momentum */ 3);
}

export {
  generate,
  is_enabled,
}
/* Stdlib__Float Not a pure module */
