// Generated by Melange

import * as Stdlib__Array from "melange/array.js";
import * as Stdlib__Float from "melange/float.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__String from "melange/string.js";
import * as Trading_core__Symbol from "../symbol.js";

const sector_etfs = [
  "XLK",
  "XLF",
  "XLE",
  "XLV",
  "XLI",
  "XLU",
  "XLC",
  "XLP",
  "XLB",
  "XLRE",
  "XLY"
];

function formation_return(s) {
  return s.return_6m - s.return_1m;
}

function generate(sectors, is_month_end, now) {
  if (!is_month_end) {
    return /* [] */ 0;
  }
  const with_formation = Stdlib__List.map((function (s) {
    return [
      s,
      formation_return(s)
    ];
  }), Stdlib__Array.to_list(sectors));
  const positive = Stdlib__List.filter((function (param) {
    return param[1] > 0.0;
  }), with_formation);
  const make_signal = function (sym, side, conf) {
    const s = Trading_core__Symbol.create(sym);
    let s$1;
    s$1 = s.TAG === /* Ok */ 0 ? s._0 : sym;
    const strength = conf > 0.8 ? ({
        TAG: /* Strong */ 0,
        _0: conf
      }) : (
        conf > 0.5 ? ({
            TAG: /* Moderate */ 1,
            _0: conf
          }) : ({
            TAG: /* Weak */ 2,
            _0: conf
          })
      );
    return {
      strategy: /* Sector_rotation */ 1,
      symbol: s$1,
      side: side,
      strength: strength,
      target_price: 0.0,
      max_position_pct: 0.15,
      timestamp: now
    };
  };
  if (Stdlib__List.length(positive) === 0) {
    return {
      hd: make_signal("BND", /* Buy */ 0, 0.6),
      tl: /* [] */ 0
    };
  }
  const sorted = Stdlib__List.sort((function (param, param$1) {
    return Stdlib__Float.compare(param$1[1], param[1]);
  }), positive);
  const top_n = Stdlib__List.filteri((function (i, param) {
    return i < 2;
  }), sorted);
  const max_fr = top_n ? Stdlib__Float.max(top_n.hd[1], 0.01) : 0.01;
  return Stdlib__List.map((function (param) {
    const conf = Stdlib__Float.min(1.0, 0.5 + 0.5 * param[1] / max_fr);
    return make_signal(param[0].symbol, /* Buy */ 0, conf);
  }), top_n);
}

function is_sector_etf(sym) {
  return Stdlib__Array.exists((function (s) {
    return Stdlib__String.equal(s, sym);
  }), sector_etfs);
}

export {
  sector_etfs,
  formation_return,
  generate,
  is_sector_etf,
}
/* Stdlib__Float Not a pure module */
