// Generated by Melange

import * as Trading_core__Money from "./money.js";
import * as Trading_core__Types from "./types.js";

const determine_phase = Trading_core__Types.phase_of_equity;

function min_position_size(phase, equity) {
  let pct;
  switch (phase) {
    case /* Micro */ 0 :
      pct = 0.05;
      break;
    case /* Small */ 1 :
      pct = 0.03;
      break;
    case /* Medium */ 2 :
      pct = 0.02;
      break;
    case /* Standard */ 3 :
      pct = 0.01;
      break;
  }
  return Trading_core__Money.of_float(equity * pct);
}

function max_positions(phase) {
  switch (phase) {
    case /* Micro */ 0 :
      return 3;
    case /* Small */ 1 :
      return 6;
    case /* Medium */ 2 :
      return 12;
    case /* Standard */ 3 :
      return 20;
  }
}

function strategies_enabled(phase) {
  switch (phase) {
    case /* Micro */ 0 :
      return {
        hd: /* Mean_reversion */ 0,
        tl: {
          hd: /* Sector_rotation */ 1,
          tl: {
            hd: /* Calendar_seasonal */ 2,
            tl: /* [] */ 0
          }
        }
      };
    case /* Small */ 1 :
      return {
        hd: /* Mean_reversion */ 0,
        tl: {
          hd: /* Sector_rotation */ 1,
          tl: {
            hd: /* Calendar_seasonal */ 2,
            tl: {
              hd: /* Momentum */ 3,
              tl: /* [] */ 0
            }
          }
        }
      };
    case /* Medium */ 2 :
    case /* Standard */ 3 :
      return {
        hd: /* Mean_reversion */ 0,
        tl: {
          hd: /* Sector_rotation */ 1,
          tl: {
            hd: /* Calendar_seasonal */ 2,
            tl: {
              hd: /* Momentum */ 3,
              tl: {
                hd: /* Market_making */ 4,
                tl: /* [] */ 0
              }
            }
          }
        }
      };
  }
}

function use_notional_orders(phase) {
  switch (phase) {
    case /* Micro */ 0 :
    case /* Small */ 1 :
      return true;
    case /* Medium */ 2 :
    case /* Standard */ 3 :
      return false;
  }
}

export {
  determine_phase,
  min_position_size,
  max_positions,
  strategies_enabled,
  use_notional_orders,
}
/* Trading_core__Money Not a pure module */
