// Generated by Melange

import * as Stdlib__Printf from "melange/printf.js";
import * as Trading_core__Time_utils from "./time_utils.js";

function apply_transition(state, transition) {
  if (/* tag */ typeof state === "number" || typeof state === "string") {
    switch (state) {
      case /* Starting */ 0 :
        if (/* tag */ typeof transition === "number" || typeof transition === "string") {
          switch (transition) {
            case /* Watchdog_connected */ 0 :
              return {
                TAG: /* Ok */ 0,
                _0: /* Warming_up */ 1
              };
            case /* Restart */ 10 :
              return {
                TAG: /* Ok */ 0,
                _0: /* Starting */ 0
              };
          }
        }
        break;
      case /* Warming_up */ 1 :
        if (/* tag */ typeof transition === "number" || typeof transition === "string") {
          switch (transition) {
            case /* Warmup_complete */ 1 :
              return {
                TAG: /* Ok */ 0,
                _0: /* Trading */ 2
              };
            case /* Restart */ 10 :
              return {
                TAG: /* Ok */ 0,
                _0: /* Starting */ 0
              };
          }
        }
        break;
      case /* Trading */ 2 :
        if (!/* tag */ (typeof transition === "number" || typeof transition === "string")) {
          if (transition.TAG === /* Flatten_triggered */ 0) {
            return {
              TAG: /* Ok */ 0,
              _0: {
                TAG: /* Cooldown */ 0,
                until: Trading_core__Time_utils.to_float(Trading_core__Time_utils.add_minutes(Trading_core__Time_utils.now(), 30.0)),
                reason: transition._0
              }
            };
          } else {
            return {
              TAG: /* Ok */ 0,
              _0: {
                TAG: /* Halted */ 1,
                reason: transition._0
              }
            };
          }
        }
        switch (transition) {
          case /* Market_close */ 3 :
            return {
              TAG: /* Ok */ 0,
              _0: /* Off_hours */ 3
            };
          case /* Watchdog_lost */ 4 :
          case /* Data_gap */ 5 :
            return {
              TAG: /* Ok */ 0,
              _0: /* Read_only */ 4
            };
          case /* Restart */ 10 :
            return {
              TAG: /* Ok */ 0,
              _0: /* Starting */ 0
            };
        }
        break;
      case /* Off_hours */ 3 :
        if (/* tag */ typeof transition === "number" || typeof transition === "string") {
          switch (transition) {
            case /* Market_open */ 2 :
              return {
                TAG: /* Ok */ 0,
                _0: /* Warming_up */ 1
              };
            case /* Restart */ 10 :
              return {
                TAG: /* Ok */ 0,
                _0: /* Starting */ 0
              };
          }
        } else if (transition.TAG === /* Kill_triggered */ 1) {
          return {
            TAG: /* Ok */ 0,
            _0: {
              TAG: /* Halted */ 1,
              reason: transition._0
            }
          };
        }
        break;
      case /* Read_only */ 4 :
        if (/* tag */ typeof transition === "number" || typeof transition === "string") {
          switch (transition) {
            case /* Data_recovered */ 6 :
            case /* Watchdog_recovered */ 7 :
              return {
                TAG: /* Ok */ 0,
                _0: /* Trading */ 2
              };
            case /* Restart */ 10 :
              return {
                TAG: /* Ok */ 0,
                _0: /* Starting */ 0
              };
          }
        } else if (transition.TAG === /* Kill_triggered */ 1) {
          return {
            TAG: /* Ok */ 0,
            _0: {
              TAG: /* Halted */ 1,
              reason: transition._0
            }
          };
        }
        break;
    }
  } else if (state.TAG === /* Cooldown */ 0) {
    if (/* tag */ typeof transition === "number" || typeof transition === "string") {
      switch (transition) {
        case /* Cooldown_expired */ 8 :
          return {
            TAG: /* Ok */ 0,
            _0: /* Warming_up */ 1
          };
        case /* Restart */ 10 :
          return {
            TAG: /* Ok */ 0,
            _0: /* Starting */ 0
          };
      }
    } else if (transition.TAG === /* Kill_triggered */ 1) {
      return {
        TAG: /* Ok */ 0,
        _0: {
          TAG: /* Halted */ 1,
          reason: transition._0
        }
      };
    }
    
  } else if (/* tag */ typeof transition === "number" || typeof transition === "string") {
    switch (transition) {
      case /* Human_acknowledged */ 9 :
      case /* Restart */ 10 :
        return {
          TAG: /* Ok */ 0,
          _0: /* Starting */ 0
        };
    }
  }
  return {
    TAG: /* Error */ 1,
    _0: Stdlib__Printf.sprintf({
      TAG: /* Format */ 0,
      _0: {
        TAG: /* String_literal */ 11,
        _0: "Invalid transition from current state",
        _1: /* End_of_format */ 0
      },
      _1: "Invalid transition from current state"
    })
  };
}

function is_trading_allowed(param) {
  if (/* tag */ (typeof param === "number" || typeof param === "string") && param === /* Trading */ 2) {
    return true;
  } else {
    return false;
  }
}

function is_data_processing_allowed(param) {
  if (/* tag */ (typeof param === "number" || typeof param === "string") && param !== /* Starting */ 0) {
    return true;
  } else {
    return false;
  }
}

function to_string(param) {
  if (!/* tag */ (typeof param === "number" || typeof param === "string")) {
    if (param.TAG === /* Cooldown */ 0) {
      return "Cooldown(" + (param.reason + ")");
    } else {
      return "Halted(" + (param.reason + ")");
    }
  }
  switch (param) {
    case /* Starting */ 0 :
      return "Starting";
    case /* Warming_up */ 1 :
      return "Warming_up";
    case /* Trading */ 2 :
      return "Trading";
    case /* Off_hours */ 3 :
      return "Off_hours";
    case /* Read_only */ 4 :
      return "Read_only";
  }
}

export {
  apply_transition,
  is_trading_allowed,
  is_data_processing_allowed,
  to_string,
}
/* No side effect */
