// Generated by Melange

import * as Caml_array from "melange.js/caml_array.js";
import * as Stdlib__Array from "melange/array.js";
import * as Stdlib__Float from "melange/float.js";

function ema(period, prev, price) {
  const alpha = 2.0 / (period + 1.0);
  return alpha * price + (1.0 - alpha) * prev;
}

function rsi(gains, losses) {
  if (losses <= 0.0) {
    return 100.0;
  }
  const rs = gains / losses;
  return 100.0 - 100.0 / (1.0 + rs);
}

function bollinger_bands(sma, std_dev, multiplier) {
  return {
    upper: sma + multiplier * std_dev,
    middle: sma,
    lower: sma - multiplier * std_dev
  };
}

function z_score(value, mean, std_dev) {
  if (std_dev <= 0.0) {
    return 0.0;
  } else {
    return (value - mean) / std_dev;
  }
}

function rvol(current_volume, avg_volume) {
  if (avg_volume <= 0.0) {
    return 0.0;
  } else {
    return current_volume / avg_volume;
  }
}

function vwap(cumulative_tp_vol, cumulative_vol) {
  if (cumulative_vol <= 0.0) {
    return 0.0;
  } else {
    return cumulative_tp_vol / cumulative_vol;
  }
}

function adx(plus_di, minus_di, prev_adx, period) {
  const di_sum = plus_di + minus_di;
  const dx = di_sum <= 0.0 ? 0.0 : Math.abs(plus_di - minus_di) / di_sum * 100.0;
  const p = period;
  return (prev_adx * (p - 1.0) + dx) / p;
}

function hurst_exponent(returns) {
  const n = returns.length;
  if (n < 20) {
    return 0.5;
  }
  const sum = Stdlib__Array.fold_left((function (acc, x) {
    return acc + x;
  }), 0.0, returns);
  const mean = sum / n;
  const deviations = Stdlib__Array.map((function (x) {
    return x - mean;
  }), returns);
  const cumdev = Caml_array.make(n, 0.0);
  for (let i = 0; i < n; ++i) {
    Caml_array.set(cumdev, i, i === 0 ? Caml_array.get(deviations, i) : Caml_array.get(cumdev, i - 1 | 0) + Caml_array.get(deviations, i));
  }
  const mx = Stdlib__Array.fold_left(Stdlib__Float.max, Stdlib__Float.neg_infinity, cumdev);
  const mn = Stdlib__Array.fold_left(Stdlib__Float.min, Stdlib__Float.infinity, cumdev);
  const r = mx - mn;
  const sum_sq = Stdlib__Array.fold_left((function (acc, d) {
    return acc + d * d;
  }), 0.0, deviations);
  const $$var = sum_sq / n;
  const s = Math.sqrt($$var);
  if (s <= 0.0) {
    return 0.5;
  }
  const rs = r / s;
  if (rs <= 0.0) {
    return 0.5;
  } else {
    return Math.log(rs) / Math.log(n);
  }
}

function adf_statistic(series) {
  const n = series.length;
  if (n < 10) {
    return 0.0;
  }
  const m = n - 1 | 0;
  const fm = m;
  let sum_xy = 0.0;
  let sum_x = 0.0;
  let sum_y = 0.0;
  let sum_x2 = 0.0;
  for (let t = 1; t < n; ++t) {
    const dy = Caml_array.get(series, t) - Caml_array.get(series, t - 1 | 0);
    const x = Caml_array.get(series, t - 1 | 0);
    sum_xy = sum_xy + x * dy;
    sum_x = sum_x + x;
    sum_y = sum_y + dy;
    sum_x2 = sum_x2 + x * x;
  }
  const denom = fm * sum_x2 - sum_x * sum_x;
  if (Math.abs(denom) < 1e-12) {
    return 0.0;
  }
  const rho = (fm * sum_xy - sum_x * sum_y) / denom;
  const intercept = (sum_y - rho * sum_x) / fm;
  let sse = 0.0;
  for (let t$1 = 1; t$1 < n; ++t$1) {
    const dy$1 = Caml_array.get(series, t$1) - Caml_array.get(series, t$1 - 1 | 0);
    const x$1 = Caml_array.get(series, t$1 - 1 | 0);
    const predicted = intercept + rho * x$1;
    const e = dy$1 - predicted;
    sse = sse + e * e;
  }
  const s2 = sse / (fm - 2.0);
  let se_rho;
  if (s2 <= 0.0) {
    se_rho = 1e-12;
  } else {
    const var_rho = s2 * fm / denom;
    se_rho = Math.sqrt(Math.abs(var_rho));
  }
  if (se_rho <= 0.0) {
    return 0.0;
  } else {
    return rho / se_rho;
  }
}

export {
  ema,
  rsi,
  bollinger_bands,
  z_score,
  rvol,
  vwap,
  adx,
  hurst_exponent,
  adf_statistic,
}
/* Stdlib__Float Not a pure module */
