// Generated by Melange

import * as Stdlib__Float from "melange/float.js";

function of_float(f) {
  return f;
}

function to_float(t) {
  return t;
}

function add(a, b) {
  return a + b;
}

function sub(a, b) {
  return a - b;
}

function mul_scalar(t, s) {
  return t * s;
}

function abs(t) {
  return Math.abs(t);
}

function $great(a, b) {
  return Stdlib__Float.compare(a, b) > 0;
}

function $less(a, b) {
  return Stdlib__Float.compare(a, b) < 0;
}

function $great$eq(a, b) {
  return Stdlib__Float.compare(a, b) >= 0;
}

const min = Stdlib__Float.min;

const max = Stdlib__Float.max;

function negate(t) {
  return -1.0 * t;
}

const zero = 0.0;

export {
  of_float,
  to_float,
  zero,
  add,
  sub,
  mul_scalar,
  abs,
  $great,
  $less,
  $great$eq,
  min,
  max,
  negate,
}
/* Stdlib__Float Not a pure module */
