// Generated by Melange

import * as Curry from "melange.js/curry.js";
import * as Stdlib__Printf from "melange/printf.js";
import * as Trading_core__Symbol from "./symbol.js";
import * as Trading_core__Time_utils from "./time_utils.js";

function apply_event(status, $$event) {
  switch (status.TAG) {
    case /* Pending */ 0 :
      switch ($$event.TAG) {
        case /* Ack */ 0 :
          return {
            TAG: /* Ok */ 0,
            _0: {
              TAG: /* Acknowledged */ 1,
              exchange_id: $$event.exchange_id,
              acked_at: $$event.timestamp
            }
          };
        case /* Partial_fill */ 1 :
        case /* Fill */ 2 :
          return {
            TAG: /* Error */ 1,
            _0: "Invalid state transition"
          };
        case /* Cancel */ 3 :
          return {
            TAG: /* Ok */ 0,
            _0: {
              TAG: /* Cancelled */ 4,
              reason: $$event.reason,
              cancelled_at: $$event.timestamp
            }
          };
        case /* Reject */ 4 :
          return {
            TAG: /* Ok */ 0,
            _0: {
              TAG: /* Rejected */ 5,
              reason: $$event.reason
            }
          };
      }
    case /* Acknowledged */ 1 :
      switch ($$event.TAG) {
        case /* Partial_fill */ 1 :
          return {
            TAG: /* Ok */ 0,
            _0: {
              TAG: /* Partially_filled */ 2,
              filled_qty: $$event.qty,
              remaining: 0.0,
              avg_price: $$event.price
            }
          };
        case /* Fill */ 2 :
          return {
            TAG: /* Ok */ 0,
            _0: {
              TAG: /* Filled */ 3,
              filled_qty: $$event.qty,
              avg_price: $$event.price,
              filled_at: $$event.timestamp
            }
          };
        case /* Cancel */ 3 :
          return {
            TAG: /* Ok */ 0,
            _0: {
              TAG: /* Cancelled */ 4,
              reason: $$event.reason,
              cancelled_at: $$event.timestamp
            }
          };
        case /* Ack */ 0 :
        case /* Reject */ 4 :
          return {
            TAG: /* Error */ 1,
            _0: "Invalid state transition"
          };
      }
    case /* Partially_filled */ 2 :
      const filled_qty = status.filled_qty;
      switch ($$event.TAG) {
        case /* Partial_fill */ 1 :
          return {
            TAG: /* Ok */ 0,
            _0: {
              TAG: /* Partially_filled */ 2,
              filled_qty: filled_qty + $$event.qty,
              remaining: 0.0,
              avg_price: $$event.price
            }
          };
        case /* Fill */ 2 :
          return {
            TAG: /* Ok */ 0,
            _0: {
              TAG: /* Filled */ 3,
              filled_qty: filled_qty + $$event.qty,
              avg_price: $$event.price,
              filled_at: $$event.timestamp
            }
          };
        case /* Cancel */ 3 :
          return {
            TAG: /* Ok */ 0,
            _0: {
              TAG: /* Cancelled */ 4,
              reason: $$event.reason,
              cancelled_at: $$event.timestamp
            }
          };
        case /* Ack */ 0 :
        case /* Reject */ 4 :
          return {
            TAG: /* Error */ 1,
            _0: "Invalid state transition"
          };
      }
    case /* Filled */ 3 :
      return {
        TAG: /* Error */ 1,
        _0: "Cannot transition from Filled state"
      };
    case /* Cancelled */ 4 :
      return {
        TAG: /* Error */ 1,
        _0: "Cannot transition from Cancelled state"
      };
    case /* Rejected */ 5 :
      return {
        TAG: /* Error */ 1,
        _0: "Cannot transition from Rejected state"
      };
  }
}

function make_client_order_id(strategy, symbol) {
  let strategy_str;
  switch (strategy) {
    case /* Mean_reversion */ 0 :
      strategy_str = "meanrev";
      break;
    case /* Sector_rotation */ 1 :
      strategy_str = "secrot";
      break;
    case /* Calendar_seasonal */ 2 :
      strategy_str = "calendar";
      break;
    case /* Momentum */ 3 :
      strategy_str = "momentum";
      break;
    case /* Market_making */ 4 :
      strategy_str = "mm";
      break;
  }
  const ts = Trading_core__Time_utils.now();
  const nonce = Math.random() * 10000.0 | 0;
  return Curry._4(Stdlib__Printf.sprintf({
    TAG: /* Format */ 0,
    _0: {
      TAG: /* String */ 2,
      _0: /* No_padding */ 0,
      _1: {
        TAG: /* Char_literal */ 12,
        _0: /* '_' */95,
        _1: {
          TAG: /* String */ 2,
          _0: /* No_padding */ 0,
          _1: {
            TAG: /* Char_literal */ 12,
            _0: /* '_' */95,
            _1: {
              TAG: /* Float */ 8,
              _0: [
                /* Float_flag_ */ 0,
                /* Float_f */ 0
              ],
              _1: /* No_padding */ 0,
              _2: {
                TAG: /* Lit_precision */ 0,
                _0: 0
              },
              _3: {
                TAG: /* Char_literal */ 12,
                _0: /* '_' */95,
                _1: {
                  TAG: /* Int */ 4,
                  _0: /* Int_x */ 6,
                  _1: {
                    TAG: /* Lit_padding */ 0,
                    _0: /* Zeros */ 2,
                    _1: 4
                  },
                  _2: /* No_precision */ 0,
                  _3: /* End_of_format */ 0
                }
              }
            }
          }
        }
      }
    },
    _1: "%s_%s_%.0f_%04x"
  }), strategy_str, Trading_core__Symbol.to_string(symbol), ts, nonce);
}

function is_terminal(status) {
  switch (status.TAG) {
    case /* Pending */ 0 :
    case /* Acknowledged */ 1 :
    case /* Partially_filled */ 2 :
      return false;
    default:
      return true;
  }
}

export {
  apply_event,
  make_client_order_id,
  is_terminal,
}
/* No side effect */
