// Generated by Melange

import * as Stdlib__Int from "melange/int.js";
import * as Stdlib__List from "melange/list.js";

function empty(equity) {
  return {
    trades: /* [] */ 0,
    equity: equity
  };
}

const five_business_days_ms = 5.0 * 24.0 * 60.0 * 60.0 * 1000.0;

function prune_old_trades(current_time, trades) {
  return Stdlib__List.filter((function (trade) {
    const age = current_time - trade.date;
    return age < five_business_days_ms;
  }), trades);
}

function add_trade(tracker, trade) {
  const trades = prune_old_trades(trade.date, {
    hd: trade,
    tl: tracker.trades
  });
  return {
    trades: trades,
    equity: tracker.equity
  };
}

function day_trade_count(tracker) {
  return Stdlib__List.length(tracker.trades);
}

function trades_remaining(tracker) {
  if (tracker.equity >= 25000.0) {
    return 999;
  }
  const used = Stdlib__List.length(tracker.trades);
  return Stdlib__Int.max(0, 3 - used | 0);
}

function can_day_trade(tracker) {
  return trades_remaining(tracker) > 0;
}

function status(tracker) {
  if (tracker.equity >= 25000.0) {
    return /* Unrestricted */ 0;
  }
  const used = Stdlib__List.length(tracker.trades);
  if (used >= 3) {
    return /* Blocked */ 1;
  } else {
    return {
      TAG: /* Restricted */ 0,
      trades_used: used
    };
  }
}

export {
  empty,
  five_business_days_ms,
  prune_old_trades,
  add_trade,
  day_trade_count,
  trades_remaining,
  can_day_trade,
  status,
}
/* No side effect */
