// Generated by Melange

import * as Caml_array from "melange.js/caml_array.js";
import * as Stdlib__Array from "melange/array.js";
import * as Stdlib__Float from "melange/float.js";
import * as Stdlib__List from "melange/list.js";

const sqrt_252 = Math.sqrt(252.0);

function mean(arr) {
  const n = arr.length;
  if (n === 0) {
    return 0.0;
  } else {
    return Stdlib__Array.fold_left((function (acc, x) {
      return acc + x;
    }), 0.0, arr) / n;
  }
}

function std_dev(arr) {
  const n = arr.length;
  if (n < 2) {
    return 0.0;
  }
  const m = mean(arr);
  const sum_sq = Stdlib__Array.fold_left((function (acc, x) {
    const d = x - m;
    return acc + d * d;
  }), 0.0, arr);
  return Math.sqrt(sum_sq / n);
}

function downside_dev(arr, target) {
  const n = arr.length;
  if (n < 2) {
    return 0.0;
  }
  const sum_sq = Stdlib__Array.fold_left((function (acc, x) {
    const d = Stdlib__Float.min(0.0, x - target);
    return acc + d * d;
  }), 0.0, arr);
  return Math.sqrt(sum_sq / n);
}

function max_drawdown(returns) {
  const n = returns.length;
  if (n === 0) {
    return 0.0;
  }
  let peak = 1.0;
  let max_dd = 0.0;
  let equity = 1.0;
  for (let i = 0; i < n; ++i) {
    equity = equity * (1.0 + Caml_array.get(returns, i));
    if (equity > peak) {
      peak = equity;
    }
    const dd = (peak - equity) / peak;
    if (dd > max_dd) {
      max_dd = dd;
    }
    
  }
  return max_dd;
}

function calculate_metrics(returns, risk_free_rate) {
  const n = returns.length;
  if (n === 0) {
    return {
      sharpe: 0.0,
      sortino: 0.0,
      max_drawdown: 0.0,
      win_rate: 0.0,
      profit_factor: 0.0,
      trade_count: 0,
      avg_win: 0.0,
      avg_loss: 0.0
    };
  }
  const daily_rf = risk_free_rate / 252.0;
  const m = mean(returns);
  const sd = std_dev(returns);
  const dd = downside_dev(returns, daily_rf);
  const sharpe = sd < 1e-12 ? 0.0 : (m - daily_rf) / sd * sqrt_252;
  const sortino = dd < 1e-12 ? 0.0 : (m - daily_rf) / dd * sqrt_252;
  const wins = Stdlib__List.filter((function (x) {
    return x > 0.0;
  }), Stdlib__Array.to_list(returns));
  const losses = Stdlib__List.filter((function (x) {
    return x < 0.0;
  }), Stdlib__Array.to_list(returns));
  const n_wins = Stdlib__List.length(wins);
  const n_losses = Stdlib__List.length(losses);
  const sum_wins = Stdlib__List.fold_left((function (a, x) {
    return a + x;
  }), 0.0, wins);
  const sum_losses = Stdlib__List.fold_left((function (a, x) {
    return a + Math.abs(x);
  }), 0.0, losses);
  const win_rate = n_wins / n;
  const profit_factor = sum_losses < 1e-12 ? (
      sum_wins > 0.0 ? Stdlib__Float.infinity : 0.0
    ) : sum_wins / sum_losses;
  const avg_win = n_wins > 0 ? sum_wins / n_wins : 0.0;
  const avg_loss = n_losses > 0 ? sum_losses / n_losses : 0.0;
  return {
    sharpe: sharpe,
    sortino: sortino,
    max_drawdown: max_drawdown(returns),
    win_rate: win_rate,
    profit_factor: profit_factor,
    trade_count: n,
    avg_win: avg_win,
    avg_loss: avg_loss
  };
}

function rolling_sharpe(returns, $$window) {
  const n = returns.length;
  if (n === 0 || $$window <= 0) {
    return 0.0;
  }
  const w = $$window < n ? $$window : n;
  const start = n - w | 0;
  const slice = Stdlib__Array.sub(returns, start, w);
  const m = mean(slice);
  const sd = std_dev(slice);
  if (sd < 1e-12) {
    return 0.0;
  } else {
    return m / sd * sqrt_252;
  }
}

export {
  sqrt_252,
  mean,
  std_dev,
  downside_dev,
  max_drawdown,
  calculate_metrics,
  rolling_sharpe,
}
/* sqrt_252 Not a pure module */
