// Generated by Melange

import * as Stdlib__List from "melange/list.js";
import * as Trading_core__Money from "./money.js";
import * as Trading_core__Position from "./position.js";
import * as Trading_core__Symbol from "./symbol.js";

const empty = {
  positions: /* [] */ 0,
  cash: Trading_core__Money.zero,
  equity: Trading_core__Money.zero,
  buying_power: Trading_core__Money.zero,
  daily_pnl: Trading_core__Money.zero,
  total_pnl: Trading_core__Money.zero
};

function total_market_value(portfolio) {
  return Stdlib__List.fold_left((function (acc, pos) {
    return Trading_core__Money.add(acc, Trading_core__Position.market_value(pos));
  }), Trading_core__Money.zero, portfolio.positions);
}

function total_unrealized_pnl(portfolio) {
  return Stdlib__List.fold_left((function (acc, pos) {
    return Trading_core__Money.add(acc, Trading_core__Position.unrealized_pnl(pos));
  }), Trading_core__Money.zero, portfolio.positions);
}

function position_count(portfolio) {
  return Stdlib__List.length(portfolio.positions);
}

function gross_exposure(portfolio) {
  return Stdlib__List.fold_left((function (acc, pos) {
    return Trading_core__Money.add(acc, Trading_core__Money.abs(Trading_core__Position.market_value(pos)));
  }), Trading_core__Money.zero, portfolio.positions);
}

function net_exposure(portfolio) {
  return Stdlib__List.fold_left((function (acc, pos) {
    return Trading_core__Money.add(acc, Trading_core__Position.market_value(pos));
  }), Trading_core__Money.zero, portfolio.positions);
}

function concentration(portfolio, symbol) {
  const eq = Trading_core__Money.to_float(portfolio.equity);
  if (eq === 0.0) {
    return 0.0;
  }
  const pos_value = Stdlib__List.fold_left((function (acc, pos) {
    if (Trading_core__Symbol.equal(pos.symbol, symbol)) {
      return Trading_core__Money.add(acc, Trading_core__Money.abs(Trading_core__Position.market_value(pos)));
    } else {
      return acc;
    }
  }), Trading_core__Money.zero, portfolio.positions);
  return Trading_core__Money.to_float(pos_value) / eq;
}

function find_position(portfolio, symbol) {
  return Stdlib__List.find_opt((function (pos) {
    return Trading_core__Symbol.equal(pos.symbol, symbol);
  }), portfolio.positions);
}

function cash_pct(portfolio) {
  const eq = Trading_core__Money.to_float(portfolio.equity);
  if (eq === 0.0) {
    return 100.0;
  } else {
    return Trading_core__Money.to_float(portfolio.cash) / eq * 100.0;
  }
}

export {
  empty,
  total_market_value,
  total_unrealized_pnl,
  position_count,
  gross_exposure,
  net_exposure,
  concentration,
  find_position,
  cash_pct,
}
/* Trading_core__Money Not a pure module */
