// Generated by Melange

import * as Stdlib__Float from "melange/float.js";
import * as Trading_core__Money from "./money.js";

function half_kelly(win_prob, avg_win, avg_loss) {
  if (avg_loss <= 0.0 || win_prob <= 0.0 || win_prob >= 1.0) {
    return 0.0;
  }
  const b = avg_win / avg_loss;
  const q = 1.0 - win_prob;
  const full_kelly = (b * win_prob - q) / b;
  const hk = full_kelly / 2.0;
  return Stdlib__Float.max(0.0, Stdlib__Float.min(0.5, hk));
}

function phase_minimum(equity, phase) {
  switch (phase) {
    case /* Micro */ 0 :
      return Stdlib__Float.max(50.0, 0.05 * equity);
    case /* Small */ 1 :
      return Stdlib__Float.max(125.0, 0.03 * equity);
    case /* Medium */ 2 :
    case /* Standard */ 3 :
      return 2000.0;
  }
}

function max_position(equity) {
  return 0.15 * equity;
}

function calculate_position_size(equity, phase, kelly_fraction, signal_confidence, param) {
  const scaled_fraction = kelly_fraction * signal_confidence;
  const raw_amount = equity * scaled_fraction;
  const min_pos = phase_minimum(equity, phase);
  const max_pos = 0.15 * equity;
  const clamped = raw_amount < min_pos ? min_pos : (
      raw_amount > max_pos ? max_pos : raw_amount
    );
  return Trading_core__Money.of_float(Stdlib__Float.min(clamped, equity));
}

export {
  half_kelly,
  phase_minimum,
  max_position,
  calculate_position_size,
}
/* Stdlib__Float Not a pure module */
