// Generated by Melange

import * as Stdlib__Float from "melange/float.js";

function of_float(f) {
  if (f >= 0.0) {
    return {
      TAG: /* Ok */ 0,
      _0: f
    };
  } else {
    return {
      TAG: /* Error */ 1,
      _0: "Price must be non-negative"
    };
  }
}

function to_float(t) {
  return t;
}

function add(a, b) {
  return a + b;
}

function sub(a, b) {
  return a - b;
}

function mul_scalar(t, s) {
  return t * s;
}

function $great(a, b) {
  return Stdlib__Float.compare(a, b) > 0;
}

function $less(a, b) {
  return Stdlib__Float.compare(a, b) < 0;
}

function $great$eq(a, b) {
  return Stdlib__Float.compare(a, b) >= 0;
}

function $less$eq(a, b) {
  return Stdlib__Float.compare(a, b) <= 0;
}

const zero = 0.0;

const compare = Stdlib__Float.compare;

export {
  of_float,
  to_float,
  zero,
  add,
  sub,
  mul_scalar,
  compare,
  $great,
  $less,
  $great$eq,
  $less$eq,
}
/* Stdlib__Float Not a pure module */
