// Generated by Melange


function classify(vix, adx) {
  if (vix > 30.0) {
    return /* Crisis */ 3;
  } else if (vix > 25.0 && adx < 20.0) {
    return /* High_vol_ranging */ 2;
  } else if (vix < 15.0 && adx > 25.0) {
    return /* Low_vol_trending */ 0;
  } else {
    return /* Normal */ 1;
  }
}

function target_allocation(param) {
  switch (param) {
    case /* Low_vol_trending */ 0 :
      return {
        mean_reversion: 0.25,
        sector_rotation: 0.10,
        calendar_seasonal: 0.05,
        momentum: 0.40,
        market_making: 0.15,
        cash: 0.05
      };
    case /* Normal */ 1 :
      return {
        mean_reversion: 0.30,
        sector_rotation: 0.15,
        calendar_seasonal: 0.10,
        momentum: 0.25,
        market_making: 0.15,
        cash: 0.05
      };
    case /* High_vol_ranging */ 2 :
      return {
        mean_reversion: 0.35,
        sector_rotation: 0.10,
        calendar_seasonal: 0.10,
        momentum: 0.10,
        market_making: 0.05,
        cash: 0.30
      };
    case /* Crisis */ 3 :
      return {
        mean_reversion: 0.10,
        sector_rotation: 0.05,
        calendar_seasonal: 0.05,
        momentum: 0.05,
        market_making: 0.05,
        cash: 0.70
      };
  }
}

function to_string(param) {
  switch (param) {
    case /* Low_vol_trending */ 0 :
      return "Low_vol_trending";
    case /* Normal */ 1 :
      return "Normal";
    case /* High_vol_ranging */ 2 :
      return "High_vol_ranging";
    case /* Crisis */ 3 :
      return "Crisis";
  }
}

export {
  classify,
  target_allocation,
  to_string,
}
/* No side effect */
