// Generated by Melange

// Patched: replaced Melange stdlib with native JS equivalents
const Stdlib = { string_of_float: (x) => String(x) };
const Stdlib__Float = { min: Math.min, compare: (a, b) => a < b ? -1 : a > b ? 1 : 0 };
const Stdlib__List = {
  fold_left: (f, acc, list) => {
    let result = acc;
    let node = list;
    while (node !== 0 && node.hd !== undefined) {
      result = f(result, node.hd);
      node = node.tl;
    }
    return result;
  }
};
import * as Trading_core__Money from "./money.js";
import * as Trading_core__Pdt_tracker from "./pdt_tracker.js";
import * as Trading_core__Portfolio from "./portfolio.js";
import * as Trading_core__Price from "./price.js";
import * as Trading_core__Types from "./types.js";

function severity(param) {
  if (/* tag */ typeof param === "number" || typeof param === "string") {
    return 0;
  }
  switch (param.TAG) {
    case /* Reduce_size */ 0 :
      return 2;
    case /* Reject */ 1 :
      return 1;
    case /* Flatten_all */ 2 :
      return 3;
    case /* Kill_switch */ 3 :
      return 4;
  }
}

function more_severe(a, b) {
  if (severity(a) >= severity(b)) {
    return a;
  } else {
    return b;
  }
}

function check_buying_power(portfolio, signal) {
  const order_value = Trading_core__Money.of_float(Trading_core__Price.to_float(signal.target_price) * signal.max_position_pct * Trading_core__Money.to_float(portfolio.equity));
  if (signal.side === /* Buy */ 0 && Trading_core__Money.$great(order_value, portfolio.buying_power)) {
    return {
      TAG: /* Reject */ 1,
      _0: "Insufficient buying power"
    };
  } else {
    return /* Allow */ 0;
  }
}

function check_position_size(config, signal) {
  if (signal.max_position_pct > config.max_position_pct) {
    return {
      TAG: /* Reject */ 1,
      _0: "Position size " + (Stdlib.string_of_float(signal.max_position_pct) + (" exceeds limit " + Stdlib.string_of_float(config.max_position_pct)))
    };
  } else {
    return /* Allow */ 0;
  }
}

function check_pdt(pdt, signal) {
  const match = signal.side;
  if (match === /* Buy */ 0 && !Trading_core__Pdt_tracker.can_day_trade(pdt)) {
    return {
      TAG: /* Reject */ 1,
      _0: "PDT restriction: no day trades remaining"
    };
  } else {
    return /* Allow */ 0;
  }
}

function check_strategy_enabled(phase, signal) {
  if (Trading_core__Types.strategy_enabled_for_phase(phase, signal.strategy)) {
    return /* Allow */ 0;
  } else {
    return {
      TAG: /* Reject */ 1,
      _0: "Strategy not enabled for current account phase"
    };
  }
}

function check_max_positions(config, portfolio, signal) {
  const match = signal.side;
  if (match === /* Buy */ 0 && Trading_core__Portfolio.position_count(portfolio) >= config.max_positions_by_phase) {
    return {
      TAG: /* Reject */ 1,
      _0: "Maximum number of positions reached"
    };
  } else {
    return /* Allow */ 0;
  }
}

function check_concentration(config, portfolio, signal) {
  const current_conc = Trading_core__Portfolio.concentration(portfolio, signal.symbol);
  if (current_conc > config.max_position_pct) {
    return {
      TAG: /* Reject */ 1,
      _0: "Symbol concentration " + (Stdlib.string_of_float(current_conc) + (" exceeds " + Stdlib.string_of_float(config.max_position_pct)))
    };
  } else {
    return /* Allow */ 0;
  }
}

function check_drawdown(config, portfolio, peak_equity) {
  const peak = Trading_core__Money.to_float(peak_equity);
  const current = Trading_core__Money.to_float(portfolio.equity);
  if (peak <= 0.0) {
    return /* Allow */ 0;
  }
  const drawdown = (peak - current) / peak;
  if (drawdown >= config.max_drawdown_flatten_pct) {
    return {
      TAG: /* Flatten_all */ 2,
      _0: "Drawdown " + (Stdlib.string_of_float(drawdown * 100.0) + "% exceeds flatten threshold")
    };
  } else if (drawdown >= config.max_drawdown_reduce_pct) {
    return {
      TAG: /* Reduce_size */ 0,
      _0: 0.5
    };
  } else {
    return /* Allow */ 0;
  }
}

function check_daily_loss(config, portfolio, daily_pnl) {
  const eq = Trading_core__Money.to_float(portfolio.equity);
  if (eq <= 0.0) {
    return /* Allow */ 0;
  }
  const loss_pct = Math.abs(Math.min(0.0, Trading_core__Money.to_float(daily_pnl))) / eq;
  if (loss_pct >= config.max_daily_loss_pct) {
    return {
      TAG: /* Reject */ 1,
      _0: "Daily loss limit exceeded"
    };
  } else {
    return /* Allow */ 0;
  }
}

function check_cash_reserve(config, portfolio) {
  const eq = Trading_core__Money.to_float(portfolio.equity);
  if (eq <= 0.0) {
    return /* Allow */ 0;
  }
  const cash_pct = Trading_core__Money.to_float(portfolio.cash) / eq;
  if (cash_pct < config.min_cash_reserve_pct) {
    return {
      TAG: /* Reject */ 1,
      _0: "Cash reserve below minimum"
    };
  } else {
    return /* Allow */ 0;
  }
}

function check_heartbeat(config, last_heartbeat, current_time) {
  const elapsed_ms = current_time - last_heartbeat;
  const timeout_ms = config.heartbeat_timeout_seconds * 1000.0;
  if (elapsed_ms > timeout_ms) {
    return {
      TAG: /* Kill_switch */ 3,
      _0: "Heartbeat timeout: " + (Stdlib.string_of_float(elapsed_ms / 1000.0) + "s since last heartbeat")
    };
  } else {
    return /* Allow */ 0;
  }
}

function evaluate(config, portfolio, signal, pdt, phase, last_heartbeat, current_time, daily_pnl, peak_equity) {
  const l4 = check_heartbeat(config, last_heartbeat, current_time);
  const l3a = check_drawdown(config, portfolio, peak_equity);
  const l3b = check_daily_loss(config, portfolio, daily_pnl);
  const l3c = check_cash_reserve(config, portfolio);
  const l2 = check_concentration(config, portfolio, signal);
  const l1a = check_buying_power(portfolio, signal);
  const l1b = check_position_size(config, signal);
  const l1c = check_pdt(pdt, signal);
  const l1d = check_strategy_enabled(phase, signal);
  const l1e = check_max_positions(config, portfolio, signal);
  return Stdlib__List.fold_left(more_severe, /* Allow */ 0, {
    hd: l4,
    tl: {
      hd: l3a,
      tl: {
        hd: l3b,
        tl: {
          hd: l3c,
          tl: {
            hd: l2,
            tl: {
              hd: l1a,
              tl: {
                hd: l1b,
                tl: {
                  hd: l1c,
                  tl: {
                    hd: l1d,
                    tl: {
                      hd: l1e,
                      tl: /* [] */ 0
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  });
}

export {
  evaluate,
}
/* Stdlib__Float Not a pure module */
