// Generated by Melange

// Patched: replaced Melange stdlib with native JS equivalents
const Stdlib__Float = { compare: (a, b) => a < b ? -1 : a > b ? 1 : 0 };
const Stdlib__Int = { compare: (a, b) => a < b ? -1 : a > b ? 1 : 0 };

function confidence(signal) {
  return signal.strength._0;
}

function is_actionable(signal) {
  const match = signal.strength;
  switch (match.TAG) {
    case /* Strong */ 0 :
    case /* Moderate */ 1 :
      return true;
    case /* Weak */ 2 :
      return false;
  }
}

function strategy_priority(param) {
  switch (param) {
    case /* Mean_reversion */ 0 :
      return 3;
    case /* Calendar_seasonal */ 2 :
      return 1;
    case /* Sector_rotation */ 1 :
    case /* Momentum */ 3 :
      return 2;
    case /* Market_making */ 4 :
      return 0;
  }
}

function compare_priority(a, b) {
  const conf_a = a.strength._0;
  const conf_b = b.strength._0;
  if (Stdlib__Float.compare(conf_a, conf_b) !== 0) {
    return Stdlib__Float.compare(conf_b, conf_a);
  }
  const pri_a = strategy_priority(a.strategy);
  const pri_b = strategy_priority(b.strategy);
  return Stdlib__Int.compare(pri_b, pri_a);
}

export {
  confidence,
  is_actionable,
  strategy_priority,
  compare_priority,
}
/* Stdlib__Float Not a pure module */
