// Generated by Melange

import * as Stdlib__Float from "melange/float.js";
import * as Stdlib__List from "melange/list.js";
import * as Trading_core__Regime from "./regime.js";
import * as Trading_core__Types from "./types.js";

function kelly_multiplier(param) {
  switch (param.TAG) {
    case /* Pilot */ 0 :
      return 0.25;
    case /* Evaluated */ 1 :
    case /* Mature */ 2 :
      return 0.50;
  }
}

function sharpe_adjustment(sharpe) {
  const raw = sharpe / 2.0;
  return Stdlib__Float.max(-0.30, Stdlib__Float.min(0.30, raw));
}

function regime_target(regime, strategy) {
  const alloc = Trading_core__Regime.target_allocation(regime);
  switch (strategy) {
    case /* Mean_reversion */ 0 :
      return alloc.mean_reversion;
    case /* Sector_rotation */ 1 :
      return alloc.sector_rotation;
    case /* Calendar_seasonal */ 2 :
      return alloc.calendar_seasonal;
    case /* Momentum */ 3 :
      return alloc.momentum;
    case /* Market_making */ 4 :
      return alloc.market_making;
  }
}

function build_allocations(regime, enabled) {
  const raw_targets = Stdlib__List.map((function (s) {
    const base = regime_target(regime, s.strategy_id);
    const adj = sharpe_adjustment(s.sharpe_60d);
    const target = base * (1.0 + adj);
    return [
      s,
      Stdlib__Float.max(0.0, target)
    ];
  }), enabled);
  const total_raw = Stdlib__List.fold_left((function (acc, param) {
    return acc + param[1];
  }), 0.0, raw_targets);
  const scale = total_raw > 1.0 ? 1.0 / total_raw : 1.0;
  const scaled = Stdlib__List.map((function (param) {
    return [
      param[0],
      param[1] * scale
    ];
  }), raw_targets);
  const n_active = Stdlib__List.length(scaled);
  const min_alloc = Stdlib__Float.max(0.10, 1.0 / Math.imul(n_active, 10));
  const constrained = Stdlib__List.map((function (param) {
    const t$p = Stdlib__Float.max(min_alloc, Stdlib__Float.min(0.60, param[1]));
    return [
      param[0],
      t$p
    ];
  }), scaled);
  const total_constrained = Stdlib__List.fold_left((function (acc, param) {
    return acc + param[1];
  }), 0.0, constrained);
  const final_scale = total_constrained > 1.0 ? 1.0 / total_constrained : 1.0;
  return Stdlib__List.map((function (param) {
    const s = param[0];
    return {
      strategy_id: s.strategy_id,
      target_pct: param[1] * final_scale,
      kelly_mult: kelly_multiplier(s.maturity)
    };
  }), constrained);
}

function allocate(regime, stats, phase) {
  const enabled = Stdlib__List.filter((function (s) {
    return Trading_core__Types.strategy_enabled_for_phase(phase, s.strategy_id);
  }), stats);
  if (enabled) {
    return build_allocations(regime, enabled);
  } else {
    return /* [] */ 0;
  }
}

export {
  kelly_multiplier,
  sharpe_adjustment,
  regime_target,
  build_allocations,
  allocate,
}
/* Stdlib__Float Not a pure module */
