// Generated by Melange

import * as Stdlib__String from "melange/string.js";

function create(s) {
  const s$1 = Stdlib__String.uppercase_ascii(s);
  if (s$1.length >= 1 && s$1.length <= 5) {
    return {
      TAG: /* Ok */ 0,
      _0: s$1
    };
  } else {
    return {
      TAG: /* Error */ 1,
      _0: "Invalid symbol: " + s$1
    };
  }
}

function to_string(t) {
  return t;
}

const equal = Stdlib__String.equal;

const compare = Stdlib__String.compare;

export {
  create,
  to_string,
  equal,
  compare,
}
/* No side effect */
