// Generated by Melange


function now(param) {
  return Date.now();
}

function of_float(f) {
  return f;
}

function to_float(t) {
  return t;
}

function diff(a, b) {
  return a - b;
}

function add_seconds(t, s) {
  return t + s * 1000.0;
}

function add_minutes(t, m) {
  return add_seconds(t, m * 60.0);
}

function is_market_hours(_t) {
  return true;
}

function is_unwind_time(_t) {
  return false;
}

function is_cancel_time(_t) {
  return false;
}

const market_open_hour = 9;

const market_open_min = 30;

const market_close_hour = 16;

const market_close_min = 0;

export {
  now,
  of_float,
  to_float,
  diff,
  add_seconds,
  add_minutes,
  market_open_hour,
  market_open_min,
  market_close_hour,
  market_close_min,
  is_market_hours,
  is_unwind_time,
  is_cancel_time,
}
/* No side effect */
